#!/usr/bin/expect
set username [lindex $argv 0]
set password [lindex $argv 1]
set src_path [lindex $argv 2]
set dest_path [lindex $argv 3]

# send_user "$username \t $password\t $src_path\t $dest_path\n"

set timeout 20
spawn scp ${username}:${src_path} $dest_path
	expect {
		"(yes/no)*" { send "yes\r"; exp_continue}
		"password" { send "${password}\r"; exp_continue}
		"No such file or directory" { send_user "error\n"; exit 1}
		 timeout { send_user "expect was timeout\n"; exit 2}
	}

exit 0
